# ShadowTrace Sentinel Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sentinel-honeypot'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule files for alerting
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 10s
    metrics_path: /metrics

  # ShadowTrace Sentinel Application
  - job_name: 'sentinel-honeypot'
    static_configs:
      - targets: ['sentinel:8080']
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    basic_auth:
      username: '${PROMETHEUS_USER}'
      password: '${PROMETHEUS_PASSWORD}'

  # PostgreSQL Database Monitoring
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Redis Monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # Docker Container Monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Blackbox Exporter (Network Probes)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://sentinel:8080/health
        - http://grafana:3000/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Alert Manager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 10s

# Remote write configuration (optional - for long-term storage)
# remote_write:
#   - url: "https://your-remote-prometheus.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Note: Storage and web configuration is handled via command line flags in docker-compose.yml
# --storage.tsdb.path=/prometheus/data
# --storage.tsdb.retention.time=30d
# --storage.tsdb.retention.size=10GB
# --web.console.templates=/etc/prometheus/consoles
# --web.console.libraries=/etc/prometheus/console_libraries
# --web.external-url=http://localhost:9090
# --web.enable-lifecycle
# --web.enable-admin-api
